# Generated by Django 4.1.7 on 2023-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_price",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                error_messages={
                    "name": {"max_length": "The price must be between 0 and 999.99."}
                },
                help_text="Maximum 999.99",
                max_digits=5,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Maximum 6 digits",
                max_digits=6,
                verbose_name="Regular price",
            ),
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sale_image",
                    models.ImageField(
                        default="images/sales/default.png",
                        help_text="Upload a sale image",
                        upload_to="images/sales/",
                        verbose_name="image",
                    ),
                ),
                ("discount_value", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("category", models.ManyToManyField(blank=True, to="product.category")),
                ("product", models.ManyToManyField(blank=True, to="product.product")),
            ],
        ),
    ]
