# Generated by Django 4.1.7 on 2023-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_discount_price_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Required and unique",
                max_length=255,
                verbose_name="Category Name",
            ),
        ),
    ]
