# Generated by Django 4.1.7 on 2023-03-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveBigIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.PositiveBigIntegerField(verbose_name="Regular price"),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specifications",
                to="product.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="productspecificationvalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specificationValue",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="productspecificationvalue",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specificationValue",
                to="product.productspecification",
            ),
        ),
    ]
