# Generated by Django 4.1.7 on 2023-03-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_product_rating_alter_product_regular_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="product.product",
            ),
        ),
    ]
