# Generated by Django 4.1.7 on 2023-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_product_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Старая цена"
            ),
        ),
    ]
